
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Prompt } from 'next/font/google';
import SideBarCard from "@/components/SideBarCard";
import { useState } from "react";
import IconButton from "@/components/IconButton";


const prompt = Prompt({
  subsets: ['latin'], 
  weight: [
    '100', '200', '300', '400', '500', '600', '700', '800', '900',
  ],
  style: ['normal', 'italic'],
  variable: '--font-prompt', 
  display: 'swap', 
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Carbon Credit Frontend",
  description: "Generated by little intern",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${prompt.variable}antialiased`}
      >
        <div className="flex h-screen">
              
          <SideBarCard  />          
          <main className="flex-1  overflow-auto">
            {children}
          </main>
          
        </div>
       
      </body>
    </html>
  );
}
