import { DataGroup } from "../types";

export const mockDataGroups: DataGroup[] = [
  {
    id: 1,
    name: "กลุ่มข้อมูลป่าไม้",
    forestData: [
      {
        id: 101,
        number: 1,
        name: "ตะเคียนทอง",
        tree_type: "Hopea odorata",
        location: "ป่าดงใหญ่",
        height: "25 เมตร",
        age: "50 ปี",
      },
      {
        id: 102,
        number: 2,
        name: "ยางนา",
        tree_type: "Dipterocarpus alatus",
        location: "ป่าทางเหนือ",
        height: "30 เมตร",
        age: "40 ปี",
      },
      {
        id: 103,
        number: 3,
        name: "ประดู่",
        tree_type: "Pterocarpus macrocarpus",
        location: "ป่าภาคอีสาน",
        height: "22 เมตร",
        age: "35 ปี",
      },
      {
        id: 104,
        number: 4,
        name: "ไม้สัก",
        tree_type: "Tectona grandis Linn. f.",
        location: "ป่าสงวนแห่งชาติ",
        height: "28 เมตร",
        age: "45 ปี",
      },
    ],
  },
  {
    id: 2,
    name: "กลุ่มข้อมูลที่ดิน",
    LandData: [
      {
        id: 201,
        number: 1,
        name: "ที่ดินโครงการ A",
        land_type: "พื้นที่อนุรักษ์",
        owner: "องค์การสวนป่า",
        area_size: "10 ไร่",
        soil_type: "ดินร่วนปนทราย",
      },
      {
        id: 202,
        number: 2,
        name: "ที่ดินโครงการ B",
        land_type: "พื้นที่เกษตรกรรม",
        owner: "กรมพัฒนาที่ดิน",
        area_size: "25 ไร่",
        soil_type: "ดินเหนียว",
      },
      {
        id: 203,
        number: 3,
        name: "ที่ดินชุมชน D",
        land_type: "พื้นที่การเรียนรู้",
        owner: "ชุมชนท้องถิ่น",
        area_size: "8 ไร่",
        soil_type: "ดินทราย",
      },
      {
        id: 204,
        number: 4,
        name: "ที่ดินฟื้นฟู E",
        land_type: "พื้นที่ฟื้นฟูระบบนิเวศ",
        owner: "กองทุนสิ่งแวดล้อม",
        area_size: "15 ไร่",
        soil_type: "ดินร่วน",
      },
    ],
  },
];
