import { DataGroup, LandPlot, LandPlotGroup } from "../types";

export const mockDataGroups: DataGroup[] = [
  {
    id: 1,
    name: "กลุ่มข้อมูลป่าไม้",
    forestData: [
      {
        id: 101,
        number: 1,
        name: "ตะเคียนทอง",
        tree_type: "Hopea odorata",
        location: "ป่าดงใหญ่",
        height: "25 เมตร",
        age: "50 ปี",
      },
      {
        id: 102,
        number: 2,
        name: "ยางนา",
        tree_type: "Dipterocarpus alatus",
        location: "ป่าทางเหนือ",
        height: "30 เมตร",
        age: "40 ปี",
      },
      {
        id: 103,
        number: 3,
        name: "ประดู่",
        tree_type: "Pterocarpus macrocarpus",
        location: "ป่าภาคอีสาน",
        height: "22 เมตร",
        age: "35 ปี",
      },
      {
        id: 104,
        number: 4,
        name: "ไม้สัก",
        tree_type: "Tectona grandis Linn. f.",
        location: "ป่าสงวนแห่งชาติ",
        height: "28 เมตร",
        age: "45 ปี",
      },
    ],
  },
  {
    id: 2,
    name: "กลุ่มข้อมูลที่ดิน",
    LandData: [
      {
        id: 201,
        number: 1,
        name: "ที่ดินโครงการ A",
        land_type: "พื้นที่อนุรักษ์",
        owner: "องค์การสวนป่า",
        area_size: "10 ไร่",
        soil_type: "ดินร่วนปนทราย",
      },
      {
        id: 202,
        number: 2,
        name: "ที่ดินโครงการ B",
        land_type: "พื้นที่เกษตรกรรม",
        owner: "กรมพัฒนาที่ดิน",
        area_size: "25 ไร่",
        soil_type: "ดินเหนียว",
      },
      {
        id: 203,
        number: 3,
        name: "ที่ดินชุมชน D",
        land_type: "พื้นที่การเรียนรู้",
        owner: "ชุมชนท้องถิ่น",
        area_size: "8 ไร่",
        soil_type: "ดินทราย",
      },
      {
        id: 204,
        number: 4,
        name: "ที่ดินฟื้นฟู E",
        land_type: "พื้นที่ฟื้นฟูระบบนิเวศ",
        owner: "กองทุนสิ่งแวดล้อม",
        area_size: "15 ไร่",
        soil_type: "ดินร่วน",
      },
    ],
  },
];





export const mockLandPlotGroups: LandPlotGroup[] = [
  {
    groupId: "f1",
    groupType: "ป่าดงดิบ",
    plots: [
      {
        id: "001",
        landNumber: "001/2565",
        budgetYear: 2565,
        deedNumber: "121314",
        surveyPage: "ทบ. 124",
        sheet: "4838 II",
        area: "3 ไร่ 2 งาน 15 ตารางวา",
        latitude: 17.385923,
        longitude: 99.123456,
        province: "ตาก",
        district: "แม่สอด",
        subdistrict: "ท่าสายลวด",
        forestType: "ป่าดงดิบ",
        trees: [
          {
            scientificName: "Tectona grandis",
            commonName: "ไม้สัก",
            family: "Lamiaceae",
            otherNames: ["สักทอง"],
            type: "ไม้เนื้อแข็ง",
            trunkCharacteristic: "ตรง มีเปลือกสีน้ำตาลเทาแตกเป็นร่อง",
            averageHeightM: 20,
            diameterCm: 35,
            approxAgeY: 15,
            quantity: 3,
            latitude: 17.385925,
            longitude: 99.123460,
          },
          {
            scientificName: "Dipterocarpus alatus",
            commonName: "ยางนา",
            family: "Dipterocarpaceae",
            otherNames: ["ยาง"],
            type: "ไม้เนื้อแข็ง",
            trunkCharacteristic: "ตรง เรือนยอดเป็นพุ่มทึบ",
            averageHeightM: 25,
            diameterCm: 40,
            approxAgeY: 20,
            quantity: 2,
            latitude: 17.385930,
            longitude: 99.123465,
          },
        ],
        surveyImages: {
          landImage: "/images/mock/land-001.jpg",
          treeImages: ["/images/mock/tree-001-1.jpg", "/images/mock/tree-001-2.jpg"],
        },
      },
      {
        id: "006",
        landNumber: "006/2565",
        budgetYear: 2565,
        deedNumber: "221314",
        surveyPage: "ทบ. 125",
        sheet: "4838 III",
        area: "2 ไร่ 1 งาน 10 ตารางวา",
        latitude: 17.386000,
        longitude: 99.123500,
        province: "ตาก",
        district: "แม่สอด",
        subdistrict: "แม่ปะ",
        forestType: "ป่าดงดิบ",
        trees: [
          {
            scientificName: "Artocarpus integer",
            commonName: "สะตอ",
            family: "Moraceae",
            otherNames: ["สะตอไทย"],
            type: "ไม้เนื้ออ่อน",
            trunkCharacteristic: "เปลือกเรียบ สีเทา",
            averageHeightM: 10,
            diameterCm: 20,
            approxAgeY: 12,
            quantity: 1,
            latitude: 17.386002,
            longitude: 99.123502,
          },
        ],
        surveyImages: {
          landImage: "/images/mock/land-006.jpg",
          treeImages: ["/images/mock/tree-006-1.jpg"],
        },
      },
    ],
    itemCount: 2,
    latestUpdate: "2025-06-20T09:30:00Z",
  },

  {
    groupId: "f2",
    groupType: "ป่าผสมผลัดใบ",
    plots: [
      {
        id: "002",
        landNumber: "002/2565",
        budgetYear: 2565,
        deedNumber: "141516",
        surveyPage: "ทบ. 210",
        sheet: "4737 I",
        area: "2 ไร่ 0 งาน 50 ตารางวา",
        latitude: 18.785400,
        longitude: 98.981700,
        province: "เชียงใหม่",
        district: "แม่ริม",
        subdistrict: "ริมใต้",
        forestType: "ป่าผสมผลัดใบ",
        trees: [
          {
            scientificName: "Hopea odorata",
            commonName: "ตะเคียนทอง",
            family: "Dipterocarpaceae",
            otherNames: ["ตะเคียน"],
            type: "ไม้เนื้อแข็ง",
            trunkCharacteristic: "เปลือกสีเทาเรียบหรือแตกเป็นสะเก็ดเล็กน้อย",
            averageHeightM: 25,
            diameterCm: 40,
            approxAgeY: 20,
            quantity: 1,
            latitude: 18.785402,
            longitude: 98.981705,
          },
        ],
        surveyImages: {
          landImage: "/images/mock/land-002.jpg",
          treeImages: ["/images/mock/tree-002-1.jpg"],
        },
      },
      {
        id: "007",
        landNumber: "007/2565",
        budgetYear: 2565,
        deedNumber: "241516",
        surveyPage: "ทบ. 211",
        sheet: "4737 II",
        area: "4 ไร่ 3 งาน 5 ตารางวา",
        latitude: 18.785450,
        longitude: 98.981750,
        province: "เชียงใหม่",
        district: "แม่ริม",
        subdistrict: "แม่แรม",
        forestType: "ป่าผสมผลัดใบ",
        trees: [
          {
            scientificName: "Albizia saman",
            commonName: "จามจุรี",
            family: "Fabaceae",
            otherNames: ["ฉำฉา"],
            type: "ไม้เนื้ออ่อน",
            trunkCharacteristic: "กิ่งแผ่กว้าง เปลือกสีเทา",
            averageHeightM: 18,
            diameterCm: 50,
            approxAgeY: 25,
            quantity: 3,
            latitude: 18.785452,
            longitude: 98.981752,
          },
          {
            scientificName: "Dipterocarpus tuberculatus",
            commonName: "ยางกราด",
            family: "Dipterocarpaceae",
            otherNames: ["ยางนาเล็ก"],
            type: "ไม้เนื้อแข็ง",
            trunkCharacteristic: "เปลือกแตกสะเก็ดลึก",
            averageHeightM: 22,
            diameterCm: 30,
            approxAgeY: 15,
            quantity: 2,
            latitude: 18.785455,
            longitude: 98.981755,
          },
        ],
        surveyImages: {
          landImage: "/images/mock/land-007.jpg",
          treeImages: ["/images/mock/tree-007-1.jpg", "/images/mock/tree-007-2.jpg"],
        },
      },
    ],
    itemCount: 2,
    latestUpdate: "2025-06-19T15:00:00Z",
  },


];
